### ISSUE TITLE
Decision task should declare artifacts in task payload

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskgraph#154]
If a decision task fails, e.g. like [this](https://community-tc.services.mozilla.com/tasks/eERL3uXBSKa-sSbM2Hgr1Q) one, because of missing scopes when submitting a task, it would be useful for the task definition to be persisted so that a user has full context on the content of the task that could not be submitted.

It looks like taskgraph submits `public/task-graph.json`, `public/target-tasks.json` etc at runtime, rather than declaring them as task artifacts. This means, if the task fails for any reason before they are dynamically uploaded, the task will not persist this information.

If this is changed, so that the task definition includes the list of artifacts that the decision task intends to publish, they will be persisted, even if the task fails, which will make debugging easier.

**Comment by ahal** [comment]
The linked task looks like it failed prior to the Taskgraph being generated, so there were no artifacts to upload as they didn't exist yet. I believe if there were an error that happened during generation then the artifacts that were output up to that point should be accessible. Also the Decision task definition is defined in `.taskcluster.yml`, so any artifacts you want uploaded should be declared there (I believe if you've copy/pasted from elsewhere, this should be set up already).

@petemoore does that make sense? I'm going to resolve this, but let me know if I'm misunderstanding the issue here and we can re-open.
