### ISSUE TITLE
Cached tasks don't work for pull-requests on level 1-only repositories

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#222]
There's some logic in Taskgraph such that the index used for cached tasks in pull request gets elevated to level 3:
https://github.com/taskcluster/taskgraph/blob/f21088f16bf2ad4f9b2973297bccec13b5051a01/src/taskgraph/util/cached_tasks.py#L61

We do this so PRs use cached tasks that were generated from a push (rather than another PR). However for repos where everything is level 1 (including pushes), these index routes will never exist and we'll never optimize the cached_task away.

Then again using cached_tasks in a level-1 only repo means that PRs could overwrite index tasks from pushes. One possible way of fixing this would be to add the `tasks_for` value to the index in this circumstance. Or maybe it's easiest to say that cached_tasks aren't supported in level-1 only repos.

**Comment by bhearsum** [comment]
An interesting wrinkle I discovered here is where something starts off level 3, and then moves to level 1 (as we did with https://github.com/mozilla/firefox-translations-training). We ended up with a bunch of level 3 caches, and started getting very unexpected rebuilds of tasks in PRs when they started to expire.

Although it's quite rare to go from level 3 to level 1, it highlights how hacky the code around [cache level for github pull requests is](https://github.com/taskcluster/taskgraph/blob/d8f608f720b4598fdc5a54440b40befdca0ea489/src/taskgraph/util/cached_tasks.py#L54-L66). That block forces the usage of level 3 caches for pull requests without consideration for how the repositories is configured (which taskgraph doesn't even know about...).

Not supporting cached tasks on PRs is not really great. Any situation where, eg: you have an expensive toolchain to build wastes money and slows down development.

Adding `tasks_for` in the index route isn't a terrible idea, but it will require a bit more specialized code to make pull requests still use cached tasks from pushes? (Because we no longer just use `level`, we need to specifically at `push` - but only for pull requests...)

A potential alternative might be to avoid using level 1 both for pushes and pull requests -- and use level 2 for pushes instead. That way we have segregated caches and might even be able to get rid of the hack cited above?

**Comment by ahal** [comment]
Another idea I just had was we could create a new route for cached tasks that include the branch name. Then PRs can be configured to use the cached task for whatever branch they are based on (or maybe just always the default branch?)

This feels nicer to me than using `tasks_for`.

I still like the idea of using level 2 to denote pushes, but that's a bigger change that will likely require an RFC and an RRA.

**Comment by ahal** [comment]
Actually I think this is even easier than that.. If we simply stop indexing PR cached tasks in the same spot as non-PR cached tasks, then we can "trust" level 1 pushes in the original location no problem.

**Comment by bhearsum** [comment]
> Actually I think this is even easier than that.. If we simply stop indexing PR cached tasks in the same spot as non-PR cached tasks, then we can "trust" level 1 pushes in the original location no problem.

Hmm...I think you're right! If I understand correctly, the reason we force level 3 or up for pull requests is because we can't trust level 1...so if we remove that we can remove the hack, and always allow PRs to look for cached tasks on any level (in addition to their own yet-to-be-named cache namespace)?

(For some reason I thought the idea of a unique namespace for PRs wouldn't have allowed us to remove that hack...but if it does it simplifies a lot of things.)

**Comment by ahal** [comment]
I *think* the mentioned PR will fix both this issue and #359. Would be great to get a second set of eyes on it though.
