### ISSUE TITLE
Support `single_dep` and `multi_dep` functionality

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#227]
The `multi_dep` and `single_dep` loaders (and related transforms) are some of the most widely copied Taskgraph logic from project to project. We've mentioned upstreaming this into Taskgraph countless times! However, over the years I've come to realize that this loader is unnecessary and overly complicated (most recently while working on https://github.com/mozilla-releng/mozilla-taskgraph/pull/7 in conjunction with the linked `firefox-android` PR).

Essentially it's doing too much at once, building upstream artifacts, copying attributes, resolving keys. The root issue is that it adds a lot of complexity right up front, which every later transform then needs to deal with. Instead we should add complexity little by little, and only as needed.

I'm still formulating thoughts here, but I think my rough plan is to:

1. Add transforms for adding dependencies given a set of kinds.
2. Add a utility file for deriving `upstream-artifacts` from a task's dependencies.
3. Add transforms for copying attributes from a `primary-dep`.
4. Push more logic into the `scriptworker` payload builders.

I believe with the above pieces, we'll be able to completely obsolete the `single_dep` and `multi_dep` loaders and replace it with a much simpler and easy to follow setup.

**Comment by bhearsum** [comment]
Maybe you omitted it because it's fairly trivial to deal with in transforms already, and we may not need or want a generic method, but just for the sake of completeness I'll note that the other major thing that `multi_dep` does is handles [chunking and fanning out tasks](https://searchfox.org/mozilla-central/source/taskcluster/gecko_taskgraph/loader/multi_dep.py#123-236) (eg: by locale, partner repack, et. al). The new [split_by_locale](https://searchfox.org/mozilla-central/rev/31f5847a4494b3646edabbdd7ea39cb88509afe2/taskcluster/gecko_taskgraph/transforms/split_by_locale.py) transform in Gecko is an example of how to do this in transforms.

**Comment by ahal** [comment]
Ah yes, good call out!
