### ISSUE TITLE
Re-name ci directory and move config.yml

### ISSUE THREAD

**Issue by gabrielBusta** [taskcluster/taskgraph#340]
@taskcluster/releng

As we expand the use of `taskcluster/taskgraph` beyond continuous integration, it seems like a good time to consider some directory re-naming to make the structure more intuitive and aligned with its broader application.

I'd like to propose the following:

1. Change `taskcluster/ci` to `taskcluster/kinds`
2. Move `taskcluster/ci/config.yml` to `taskcluster/config.yml`

In addition to these, it might be a good time to consider incorporating support for `.taskcluster` and/or `.github/taskcluster`

Should we make the directory configurable in `taskcluster.yml`, default to `taskcluster`, and allow `.taskcluster` and `.github/taskcluster` as options?

**Comment by ahal** [comment]
> Should we make the directory configurable in taskcluster.yml, default to taskcluster, and allow .taskcluster and .github/taskcluster as options?

Taskgraph already supports a `--root` command line flag that in-theory allows this dir to live anywhere. So in that sense it's already configuratble via `.taskcluster.yml`. But in practice, I wouldn't be surpised if using this flag causes issues with various parts of Taskgraph.

**Comment by gabrielBusta** [comment]
Oh in that case that sounds like a separate issue. I will give it a go and see what breaks.

**Comment by gabrielBusta** [comment]
But, if it is already configurable, I think we can batch 1 and 2. Any other changes/issues it would make sense to batch in?

**Comment by ahal** [comment]
Like into the same release you mean?

If we're breaking backwards compat for non-essential refactorings anyway.. I've long wanted to rename the `job` transforms to `run` :p

**Comment by JohanLorenzo** [comment]
Hey there! 

I like this change because it makes much more sense to newcomers!

For what it's worth, I implemented these 2 changes in the [taskgraph fork for Gitlab CI](https://gitlab.com/jobgraph-dev/jobgraph). Good news is: the changes themselves are not too hard to implement: 
 * [Rename `gitlab-ci/ci` to `gitlab-ci/stages`](https://gitlab.com/jobgraph-dev/jobgraph/-/commit/2264a8a5170d65a1ccc93c6d336ef12b4013bd82)
 * [Move `config.yml` out of the stages folder](https://gitlab.com/jobgraph-dev/jobgraph/-/commit/0304a17e109ecfb108166f01fdf8f3cebe8718d2)

Thus, the biggest part would be to convert all downstream repositories to the new dir tree.

**Comment by gabrielBusta** [comment]
> Like into the same release you mean?

Yes, this is what I mean. Since it's a breaking backwards compat.

> If we're breaking backwards compat for non-essential refactorings anyway.. I've long wanted to rename the `job` transforms to `run` :p

I like this @ahal, I think #27 would help newcomers as well.

@JohanLorenzo those changes look straight forward. The biggest part is definitely adjusting the downstream trees.

fwiw it'll get easier by rote and we only have to apply the changes when we bump taskgraph on each repository.

I see there's one more issue with the BREAKING CHANGE label. Its #24.
